# Generated by Django 5.0 on 2023-12-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
